### ISSUE TITLE
Add easy way to copy the generated url

### ISSUE THREAD

**Issue by mslepko** [mslepko/notion-widgets#188]

**Comment by Potato-29** [comment]
We can add a button at the bottom, that can copy the URL to user's clipboard instead of displaying the whole URL on screen

**Comment by mslepko** [comment]
Yes, but I please keep the URL displayed as well

Something like this 
![Screenshot 2024-10-01 at 10 11 32](https://github.com/user-attachments/assets/d2949d1a-b20d-4eda-a02f-98595dc0d268)

**Comment by Potato-29** [comment]
yeah this looks better, will do this

**Comment by Potato-29** [comment]
![image](https://github.com/user-attachments/assets/ec2dc670-efea-4482-bafd-7adc59242d62)

![image](https://github.com/user-attachments/assets/bdb9dc23-fc40-4157-bbc8-dcdfa725be9e)

looks good?

**Comment by Potato-29** [comment]
great, I'll raise a PR then
