### ISSUE TITLE
Disk Usage Analyzer

### ISSUE THREAD

**Issue by pratikj697** [mslepko/notion-widgets#278]
The goal of this project is to analyze disk usage in a specified directory by identifying and tracking the size of files and reporting the largest files found within the directory.

This system efficiently scans a directory and all of its subdirectories, identifying files and their sizes. The solution includes handling common edge cases such as missing files or permission issues, and returns the N largest files in the directory.

Requirements:
1. Directory Traversal:
Traverse all files and subdirectories in a given directory and compute their sizes.
2. Sorting:
Sort files by size in descending order, and display the largest files.

Edge Cases:
Handle cases where certain files or directories are inaccessible (permissions error).

Can you please assign this task to me under HacktoberFest 2024.

**Comment by mslepko** [comment]
@pratikj697 sorry but I think it's not relevant to this project and as this might need some additional permission from the users I don't want to include is as a widget to use with Notion
