### ISSUE TITLE
Date/Time Widget - show/hide labels

### ISSUE THREAD

**Issue by mslepko** [mslepko/notion-widgets#44]

**Comment by Potato-29** [comment]
Hi @mslepko, could you provide some details as to what needs to done? I would like to work on this :)

**Comment by mslepko** [comment]
Currently, when you visit a URL to copy from Date Widget page
![Screenshot 2024-09-27 at 10 50 24](https://github.com/user-attachments/assets/c2317110-d4ee-4da6-af79-3e0bcc4be066)

All those labels are visible
Time: 
Date:
Day: 
Quarter: 
![Screenshot 2024-09-27 at 10 51 48](https://github.com/user-attachments/assets/f30513fd-d32e-491d-8b0c-3ad0788229a6)

I'd like to have the ability for the user to choose if those labels should be displayed or not

**Comment by Potato-29** [comment]
you mean something like this? The labels hidden and only the values are visible?

![image](https://github.com/user-attachments/assets/9d61f8b7-88dc-4672-8e05-09f0760ebafa)

**Comment by mslepko** [comment]
Yes, but it should be an option to show/hide labels 
![Screenshot 2024-09-27 at 11 24 50](https://github.com/user-attachments/assets/f2032114-8656-4687-91e3-c81d0b2ec478)

**Comment by Potato-29** [comment]
Got it now, I'll do this for you

**Comment by Potato-29** [comment]
Hi @mslepko , I've added this feature as well, I'll raise the PR once hactoberfest starts :)

**Comment by Potato-29** [comment]
assign to me, so I can raise a PR
