### ISSUE TITLE
Improve layout

### ISSUE THREAD

**Issue by mslepko** [mslepko/notion-widgets#49]
Currently on date/time widget when you choose to hide items the screen will jump a bit

**Comment by Potato-29** [comment]
Hi @mslepko, I can fix this for you.

**Comment by Potato-29** [comment]
Hi @mslepko, fixed this issue, please assign this so I can raise a PR

**Comment by Potato-29** [comment]
@mslepko, according to hacktoberfest, my PR must be created between 1st Oct to 31st Oct, Is it fine if I create this PR during that window?
